version: '2'

services:
   mariadb:
     image: mariadb:latest
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: XXXXXXXXXXXXXXXX
       MYSQL_DATABASE: wordpress

   wordpress:
     links:
       - mariadb:mysql
     image: wordpress:latest
     ports:
       - "8080:80"
     environment:
       WORDPRESS_DB_HOST: mariadb:3306
       WORDPRESS_DB_PASSWORD: XXXXXXXXXXXXX
     working_dir: /var/www/html
     volumes:
      - ./code:/code
      - ./html:/var/www/html
